### ISSUE TITLE
Unable to login using username.

### ISSUE THREAD

**Issue by velayudhamv** [ubuntu/aad-auth#201]
Unable to login using username. Have to use username@domain.com. Is there any parameters that can be used in aad.conf file like that available in sssd.conf? 
Also when setting homedir to home/%u doesn’t seem to create homedir. Had to use home/%f and it created fine.

**Comment by denisonbarbosa** [comment]
Hey @velayudhamv, thanks for reporting this issue! Sadly, there isn't any parameters in `aad.conf` to set a default domain for the user, so you need to use the fully qualified username in order to authenticate. It could be a nice thing to add, but we still need to check its interaction with the one that can be added in `sssd.conf` and how to handle possible conflicts.

For the homedir issue, can you share the logs so we can have a better understanding of what could be happening?

**Comment by velayudhamv** [comment]
Which log would you require to check?

**Comment by velayudhamv** [comment]
I rebuilt the machine and now it works fine after editing the conf file.
