### ISSUE TITLE
Why backporting to 22.04 LTS is not supported now?

### ISSUE THREAD

**Issue by velayudhamv** [ubuntu/aad-auth#417]
Earlier it was mentioned that this feature will be backported to support 22.04LTS but now it has been mentioned that Azure AD User Authentication is only included in Ubuntu 23.04 and 23.10.

Any reason why this feature was removed to not support 22.04LTS? We have an entire estate with LTS running devices only and would require this feature to migrate our devices from on prem AD to Azure AD based.

**Comment by u-ways** [comment]
Hello, I would be interested in understanding this as well, please. We have the exact same issue above and would risk steering us off the LTS. Note #305 is relevant to  this.

**Comment by velayudhamv** [comment]
As in our enterprise, we prefer long term support and so moving away from LTS is risky for us and would really appreciate the AAD join support in LTS.

**Comment by local-optimum** [comment]
Hi folks, Ubuntu PM here, we're keen to ensure that Ubuntu delivers the most integrated experience with customers' preferred identity providers and to that end we introduced the first implementation of an AAD authentication flow in Ubuntu 23.04. However after trialing this implementation with customers we realised a few shortcomings. 

We are working on a new broker based on the OIDC device authorisation grant flow which will deliver:

- increased security and full compliance to Oauth2 RFC 8628
- support for both desktop and server environments
- better administrator experience
- support for more MFA flows

We are hoping to provide the new broker in Ubuntu 24.04.
Since sensitive areas of the stack (such as GDM) need to be updated to support MFA flows, it is not clear if it will be possible to backport this solution to earlier LTS releases

**Comment by velayudhamv** [comment]
@local-optimum Thanks for your prompt response. We may have to wait a bit longer than expected, if we want to migrate our 22.04LTS devices from on-prem AD to Azure AD then.
Any official release date for 24.04 LTS and support?

**Comment by local-optimum** [comment]
Ubuntu 24.04 LTS will release on April 25th 2024, we aim to have this feature available there at launch with the standard caveates of in-development roadmap items being subject to change. Please follow this repo for the latest progress https://github.com/ubuntu/authd
