### ISSUE TITLE
Improve consistency of cache offline expiration

### ISSUE THREAD

**Issue by denisonbarbosa** [ubuntu/aad-auth#42]
Right now, the cache considers the value 0 as a signal to not be cleaned. However, this is also the value that is used to block offline authentication. This means that users can not authenticate offline, despite being the cache.
This could be solved by dividing those functionalities in two different sets of values (e.g. 0 to prevent offline authentication and negative numbers to prevent the cache from being cleaned, or vice-versa).

**Comment by didrocks** [comment]
There is a catch with the user not being in the cache (for 0 for instance): we still need the user in the db for nss to be able to resolve the user. Can you think of a compatible clean policy then?

**Comment by denisonbarbosa** [comment]
Instead of handling it with offline_credential values, we could add another configuration attribute (e.g. allow_offline_authentication or prevent_offline_authentication) in aad.conf. If set to disallow, we can still add authenticated users to the cache, but disable the option to authenticate a user with cache values. This way, we can avoid having a misleading configuration and a more consistent offline expiration value (that would handle only the offline expiration side of the cache) while still allowing nss to use the cache for resolving the user.

**Comment by didrocks** [comment]
But this may create even more confusion:
* What happens if I set the first element to 0? This would mean "no cache", but we can’t afford having no cache because it means then we don’t have NSS resolution.
* If we set it to "allow", then, the time we allow offline login is controlled by the other settings, and what if we set to "allow" while the other has a negative or 0 value?

So, separating doesn’t fully solve it (I think more and more we should rename the option), but I don’t have any definitive ideas on it.
